USE [master]
GO

/****** Object:  Database [FootballManager]    Script Date: 17-Jul-17 20:42:45 ******/
CREATE DATABASE [FootballManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FootballManager', FILENAME = N'D:\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\FootballManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FootballManager_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\FootballManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FootballManager] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FootballManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FootballManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FootballManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FootballManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FootballManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FootballManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [FootballManager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FootballManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FootballManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FootballManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FootballManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FootballManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FootballManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FootballManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FootballManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FootballManager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FootballManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FootballManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FootballManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FootballManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FootballManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FootballManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FootballManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FootballManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FootballManager] SET  MULTI_USER 
GO

ALTER DATABASE [FootballManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FootballManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FootballManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FootballManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FootballManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FootballManager] SET QUERY_STORE = OFF
GO

USE [FootballManager]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [FootballManager] SET  READ_WRITE 
GO

